[package]
name = "espterm-emulator"
version = "0.1.0"
authors = ["cpsdqs <cpsdqs@gmail.com>"]

[dependencies]
lazy_static = "1.0"
libc = "0.2"
pty = "0.2"
qstring = "0.6"
regex = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
ws = "0.7"
