[package]
name = "espterm-emulator"
version = "0.1.0"
authors = ["cpsdqs <cpsdqs@gmail.com>"]
license = "MIT"
build = "build.rs"

[lib]
name = "espterm_emulator"
crate-type = ["dylib"]

[build-dependencies]
neon-build = "0.1.20"

[dependencies]
neon = "0.1.20"
